name = "GtkSourceWidget"
uuid = "6ceb4976-07da-5329-b1cb-20978726f1f4"

[deps]
Gtk = "4c0ca9eb-093a-5379-98c5-f87ac0bbbf44"
GtkSourceView_jll = "bf9c6edb-e643-5064-a5c3-0f96a1285812"

[compat]
Gtk = "1"
GtkSourceView_jll = "4.4.0"
julia = "1.3"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
